# Generated by Django 3.0.2 on 2021-04-04 21:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0003_auto_20210404_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.IntegerField()),
                ('sell_value', models.FloatField()),
                ('percentage', models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('delivery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Delivery')),
            ],
        ),
    ]
