# Generated by Django 3.0.2 on 2021-04-05 02:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0005_sale'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.FloatField()),
                ('expense', models.FloatField()),
                ('expense_description', models.TextField()),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sale.Sale')),
            ],
        ),
    ]
