# Generated by Django 3.0.2 on 2021-04-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sale', '0006_saleitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_link',
            field=models.URLField(blank=True),
        ),
    ]
